# fly.toml app configuration file for rust-base Axum API
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "rust-base-api"
primary_region = "sin"  # Singapore region (change as needed)
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "sqlx migrate run"  # Run migrations on deploy

[env]
  PORT = "3000"
  RUST_LOG = "info"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

# VM Configuration
[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Scaling configuration
[scaling]
  min_machines_running = 0
  max_machines_running = 3
